# **Introdução à Biblioteca NumPy em Python**

O NumPy é uma biblioteca em Python para computação científica, especialmente para cálculos numéricos em larga escala e manipulação de arrays multidimensionais. O nome NumPy é uma abreviação de “Numeric Python” (Python Numérico).

O NumPy oferece uma ampla gama de funções e operações matemáticas, incluindo funções de álgebra linear, transformadas de Fourier, geração de números aleatórios, estatísticas e muito mais.

Uma das principais vantagens do NumPy é sua capacidade de lidar com grandes quantidades de dados de maneira rápida e eficiente, graças à implementação de operações vetorizadas. Essas operações permitem que cálculos em grandes conjuntos de dados sejam executados de forma eficiente e com menos código.

# **O que é um array em NumPy?**

Em NumPy, um array é um tipo de objeto que representa uma coleção de elementos homogêneos (ou seja, do mesmo tipo) organizados em uma ou mais dimensões. Esses arrays podem ser de diferentes formas (ou seja, números de dimensões e tamanhos), e cada elemento em um array é indexado por uma tupla de inteiros não negativos.

Por exemplo:

Array de uma dimensão:

`1 5 9 3 2 4 2 1 6 5 7 0 8`

Array de duas dimensões (três linhas por quatro colunas, 3×4):


```
1 5 9 3
2 4 2 1
6 5 7 0
```

# **Tutorial básico de NumPy**

Em suma, os arrays em NumPy são usados para representar dados em muitas áreas diferentes, incluindo processamento de imagens, aprendizado de máquina e ciência de dados em geral.

Para criar arrays em NumPy empregamos a função `numpy.array()` Veremos 10 exemplos de uso da biblioteca Numpy a seguir.


# 1. Como instalar o NumPy

Antes de começar a usar o NumPy, precisamos instalá-lo em seu sistema. Podemos instalar o pacote usando o gerenciador de pacotes pip 

In [4]:
# Como instalar biblioteca NumPy
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# 2. Importar o NumPy

Depois de instalar o NumPy, precisamos importá-lo para poder usar a biblioteca e suas funções:

In [7]:
# importanto a biblioteca
import numpy as np

# 3. Criação de arrays

O NumPy é usado principalmente para trabalhar com arrays multidimensionais. Podemos criar um array NumPy usando a função `array():`

In [6]:
# Esse código cria um array NumPy unidimensional com os valores [1, 2, 3, 4, 5].
x = np.array([1, 2, 3, 4,5])
print(x)

[1 2 3 4 5]


In [8]:
# Também podemos criar um array NumPy bidimensional passando uma lista de listas para a função array():
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


# 4. Acessar elementos de um array

Podemos acessar os elementos de um array NumPy usando seus números de índice, que iniciam em 0:

In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x[0]) # números de índice, que iniciam em 0
print(x[1]) # números de índice, que iniciam em 1

1
2


In [10]:
# Também podemos acessar elementos de um array bidimensional usando índices de linha e coluna:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0, 0]) # 1
print(x[0, 1]) # 2
print(x[1, 0]) # 3

1
2
4


# 5. Operações em arrays

O NumPy permite realizar operações em arrays de forma rápida e eficiente. Por exemplo, podemos adicionar dois arrays NumPy da seguinte maneira:

In [11]:
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
x3 = x1 + x2 # somando as duas variaveis
print(x3)

[5 7 9]


# 6. Funções matemáticas

O NumPy também oferece muitas funções matemáticas, como por exemplo a função `sqrt()` para calcular a raiz quadrada de um array, `exp()` para calcular a exponencial de um array e `sin()` para calcular o seno de um array:

In [13]:
x = np.array([1, 2, 3])
print(np.sqrt(x))
print(np.exp(x))
print(np.sin(x))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


# 7. Reshape de arrays

Podemos alterar a forma de um array usando a função `reshape()`

Esse código irá criar um novo array bidimensional de formato 2 x 3, a partir de um array unidimensional, com os valores:

In [14]:
x = np.array([1, 2, 3, 4, 5, 6])
novo_x = x.reshape(2, 3)
print(novo_x)

[[1 2 3]
 [4 5 6]]


# 8. Ordenação de arrays

O NumPy também oferece funções para ordenação de arrays:

Usando a função `sort()` isso criará um novo array com os valores do array original ordenados em ordem crescente.


In [15]:
x = np.array([3, 2, 1, 5, 4])
novo_x = np.sort(x)
print(novo_x)

[1 2 3 4 5]
